In [1]:
import numpy as np
import pandas as pd
import re
from gensim.models.fasttext import FastText
from gensim.test.utils import get_tmpfile
from tqdm import tqdm

d:\python371\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
data = pd.read_csv('dataset_nlp_field.csv', encoding = 'utf-8')
data['meaning_ru']

d:\python371\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,1,7,15,16,17) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


0             никогда
1           ни за что
2        см. АБÁДАЛIИ
3            абазинец
4            абазинец
             ...     
72760             NaN
72761             NaN
72762             NaN
72763             NaN
72764             NaN
Name: meaning_ru, Length: 72765, dtype: object

In [4]:
data['new'] = data['meaning_ru'].apply(lambda x: None if re.match(r'см.*', str(x)) else x)
data['new']

0          никогда
1        ни за что
2             None
3         абазинец
4         абазинец
           ...    
72760          NaN
72761          NaN
72762          NaN
72763          NaN
72764          NaN
Name: new, Length: 72765, dtype: object

In [5]:
print(len(data))
data = data.dropna(subset=['new'])
print(len(data))

72765
34329


In [6]:
from gensim.models.keyedvectors import FastTextKeyedVectors, KeyedVectors
# from gensim.models.fasttext import FastText
# model = FastText.load('model.model')
# from gensim.models.wrappers import FastText

model = KeyedVectors.load('araneum_none_fasttextcbow_300_5_2018.model')
# https://rusvectores.org/ru/models/

In [66]:
x = []
if 'никогда' in model:
    x.append(model['никогда'])
type(model['ндаa'])

AttributeError: 'FastTextKeyedVectors' object has no attribute 'hash2index'

In [7]:
model.most_similar('никогда')

AttributeError: 'FastTextKeyedVectors' object has no attribute 'hash2index'

In [13]:
from sklearn.neighbors import NearestNeighbors


neigh = NearestNeighbors(n_neighbors=100)

In [9]:
#X = numpy.zeros(shape=(len(data['meaning_ru']),300))
X = np.zeros(shape=(len(data['new']),300))
for i, word in tqdm(enumerate(list(data['new']))):
    #print(word)
    try:
        X[i,:]= model[word]
    except AttributeError:
        X[i,:]= np.zeros(shape=(1, 300))

34329it [00:28, 1222.07it/s]


In [12]:
X

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.06717373,  0.02914021, -0.01555889, ...,  0.0101513 ,
         0.01363466,  0.04220704],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.116459  ,  0.05659711, -0.02191279, ...,  0.03256437,
         0.08351083,  0.10638119]])

In [14]:
neigh.fit(X)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=100, p=2, radius=1.0)

In [19]:
model['кот']

array([ 0.05532207, -0.03416371,  0.09553006, -0.06470148,  0.03807628,
        0.01288879, -0.05889906,  0.01471918, -0.03877266,  0.02002366,
       -0.04145822,  0.0223567 ,  0.1146071 ,  0.00771999, -0.01510936,
       -0.03636136,  0.01117184, -0.0425341 , -0.06097239,  0.03195909,
       -0.04793399,  0.05645467,  0.05659531, -0.0050471 ,  0.07197711,
       -0.08298003,  0.08937121,  0.01818784,  0.06795307, -0.0372864 ,
       -0.06513053,  0.07789685, -0.01822467,  0.06675985, -0.05263124,
       -0.00796997, -0.03543192, -0.04865527,  0.06391837,  0.01606985,
       -0.0635512 , -0.05119732,  0.03632743, -0.02915037, -0.06456284,
       -0.00932478, -0.03297231,  0.05645484, -0.06959673,  0.00174949,
        0.07978323,  0.11734015, -0.03877383,  0.08682764, -0.03376166,
        0.0033726 ,  0.0171323 ,  0.0128882 , -0.0336334 , -0.0522515 ,
       -0.0106751 ,  0.09108189,  0.05109027, -0.0986954 ,  0.02219179,
       -0.03601119,  0.03198642,  0.06793629, -0.01893481, -0.01

In [23]:
# Нужно подумать как печатать все сто и как слова а не как вектора. Сейчас он печатает координаты топ-1
print(neigh.kneighbors(model['кот'].reshape(1, -1)))

(array([[0.        , 0.        , 0.58283925, 0.58283925, 0.78919334,
        0.78919334, 0.78919334, 0.78919334, 0.80691524, 0.80691524,
        0.80691524, 0.80691524, 0.80691524, 0.80691524, 0.80691524,
        0.80691524, 0.80691524, 0.80691524, 0.80691524, 0.80691524,
        0.80691524, 0.84821045, 0.84821045, 0.84879925, 0.84879925,
        0.84879925, 0.84879925, 0.86237511, 0.86237511, 0.86237511,
        0.86237511, 0.87050295, 0.87855347, 0.90048956, 0.90048956,
        0.90353443, 0.90353443, 0.90401404, 0.90401404, 0.90401404,
        0.90601368, 0.90601368, 0.90601368, 0.90601368, 0.90601368,
        0.90601368, 0.90601368, 0.90601368, 0.90799924, 0.90799924,
        0.90799924, 0.90799924, 0.90799924, 0.91019728, 0.91164148,
        0.91906896, 0.92050088, 0.92476784, 0.92476784, 0.92476784,
        0.92476784, 0.92873042, 0.93041868, 0.93041868, 0.93041868,
        0.93482043, 0.93482043, 0.93482043, 0.93482043, 0.93521686,
        0.94363684, 0.94363684, 0.94363684, 0.9